### ISSUE TITLE
Problems about different robotic arms

### ISSUE THREAD

**Issue by baiyu858** [rail-berkeley/fmb#2]
Is it possible to train on the official dataset using imitation learning and then directly validate in real-world scenarios, even if the robotic arm is different from Franka?  Would it be necessary to collect a new dataset?

**Comment by jianlanluo** [comment]
If you are not using Franka, it would be interesting to see if fine-tuning on your new embodiment data would work. In general, it's recommended you collect a new dataset, and you can contribute to FMB
