### ISSUE TITLE
Missing data in published TFDS FMB

### ISSUE THREAD

**Issue by dunalduck0** [rail-berkeley/fmb#4]
There are only 1804 episode in the published TFDS FMB dataset: https://www.tensorflow.org/datasets/catalog/fmb

It looks only trajectories in "multi_object_manipulation" is published

**Comment by charlesxu0124** [comment]
Hello, thanks for reaching out. We noticed the issue as well, and the dataset on TFDS has been corrected. It's just that Google has not updated the catalog, so the information you see there is still old. If you load the dataset with `tfds.load("robotics:fmb", with_info=True)`, you should see that it contains 8611 episodes. Let me know if there are still issues.

**Comment by dunalduck0** [comment]
Thank you @charlesxu0124. Can I ask a clarification question? I did not download the data via TFDS; I downloaded via

```
gsutil -m cp -r gs://gresearch/robotics/fmb
```

I've got only one version 0.0.1 in the folder and the size is 356G. Is it the corrected dataset or is it still the wrong version?

**Comment by charlesxu0124** [comment]
When did you download the dataset from the bucket? It was actually just corrected this week, so you might still have the old version. I just checked and you should see the right version that's 1.17TiB at `gs://gresearch/robotics/fmb/0.0.1` now.

**Comment by dunalduck0** [comment]
Oh, no, I downloaded on 8/2 and I've noticed new data stamp of 8/5. What a race! :)

**Comment by dunalduck0** [comment]
Thank you @charlesxu0124 for correcting the data
